'use strict';
const express = require('express');
const c = require('../controllers/admin.controller');
const { requireAdmin } = require('../middleware/admin-auth');
const { adminLoginRateLimit } = require('../middleware/rate-limit');
const router = express.Router();
router.post('/admin/login', adminLoginRateLimit, c.login); router.post('/admin/logout', c.logout); router.get('/admin/me', requireAdmin, c.me);
router.use('/admin', requireAdmin);
router.post('/admin/upload', c.uploadImage);
router.get('/admin/products', c.listProducts); router.post('/admin/products', c.saveProduct); router.put('/admin/products/:id', c.saveProduct); router.delete('/admin/products/:id', c.deleteProduct);
router.get('/admin/posts', c.listPosts); router.post('/admin/posts', c.savePost); router.put('/admin/posts/:id', c.savePost); router.delete('/admin/posts/:id', c.deletePost);
router.get('/admin/orders', c.listOrders); router.get('/admin/orders/:id', c.getOrder); router.patch('/admin/orders/:id/status', c.updateOrderStatus);
router.get('/admin/store', c.getStore); router.put('/admin/store', c.updateStore);
router.get('/admin/categories', c.listCategories); router.post('/admin/categories', c.saveCategory); router.put('/admin/categories/:key', c.saveCategory); router.delete('/admin/categories/:key', c.deleteCategory);
router.get('/admin/customers', c.listCustomers);
router.get('/admin/feedback', c.listFeedback); router.post('/admin/feedback', c.saveFeedback); router.patch('/admin/feedback/:id/status', c.updateFeedbackStatus); router.delete('/admin/feedback/:id', c.deleteFeedback);
router.get('/admin/reports/profit', c.profitReport);
router.get('/admin/system', c.getSystem); router.put('/admin/system', c.updateSystem);
module.exports = router;