import { request } from './client';

const options = (method, body) => ({ method, body: JSON.stringify(body) });
export const adminLogin = (username, password) => request('/admin/login', options('POST', { username, password }));
export const adminLogout = () => request('/admin/logout', { method: 'POST' });
export const adminMe = () => request('/admin/me');
export const getAdminProducts = () => request('/admin/products');
export const createAdminProduct = (data) => request('/admin/products', options('POST', data));
export const updateAdminProduct = (id, data) => request(`/admin/products/${id}`, options('PUT', data));
export const deleteAdminProduct = (id) => request(`/admin/products/${id}`, { method: 'DELETE' });
export const uploadAdminImage = (dataUrl) => request('/admin/upload', { method: 'POST', body: JSON.stringify({ dataUrl }) });
export const getAdminPosts = () => request('/admin/posts');
export const createAdminPost = (data) => request('/admin/posts', options('POST', data));
export const updateAdminPost = (id, data) => request(`/admin/posts/${id}`, options('PUT', data));
export const deleteAdminPost = (id) => request(`/admin/posts/${id}`, { method: 'DELETE' });
export const getAdminOrders = () => request('/admin/orders');
export const getAdminOrder = (id) => request(`/admin/orders/${id}`);
export const updateAdminOrderStatus = (id, status) => request(`/admin/orders/${id}/status`, options('PATCH', { status }));
export const getStoreSettings = () => request('/admin/store');
export const updateStoreSettings = (data) => request('/admin/store', options('PUT', data));
export const getAdminCategories = () => request('/admin/categories');
export const createAdminCategory = (data) => request('/admin/categories', options('POST', data));
export const updateAdminCategory = (key, data) => request(`/admin/categories/${encodeURIComponent(key)}`, options('PUT', data));
export const deleteAdminCategory = (key) => request(`/admin/categories/${encodeURIComponent(key)}`, { method: 'DELETE' });
export const getAdminCustomers = () => request('/admin/customers');
export const getAdminFeedback = () => request('/admin/feedback');
export const createAdminFeedback = (data) => request('/admin/feedback', options('POST', data));
export const updateAdminFeedbackStatus = (id, status) => request(`/admin/feedback/${id}/status`, options('PATCH', { status }));
export const deleteAdminFeedback = (id) => request(`/admin/feedback/${id}`, { method: 'DELETE' });
export const getProfitReport = () => request('/admin/reports/profit');
export const getSystemSettings = () => request('/admin/system');
export const updateSystemSettings = (data) => request('/admin/system', options('PUT', data));