-- LƯU Ý SQL PORTABLE: COALESCE, NULLIF, GREATEST, LEAST là construct của parser (không có entry
-- trong pg_proc) — BẮT BUỘC viết KHÔNG tiền tố schema; dạng có tiền tố "pg_catalog" + ".coalesce"
-- sẽ lỗi 42883 "function ... does not exist" trên PostgreSQL thật. Chúng không phụ thuộc search_path
-- nên vẫn an toàn trong hàm SECURITY DEFINER SET search_path = ''. Các hàm THẬT (btrim, upper,
-- sum, lpad, now...) thì vẫn giữ tiền tố pg_catalog. như bên dưới.
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;
DO $block$
DECLARE v_schema text;
BEGIN
  SELECT n.nspname INTO v_schema
  FROM pg_catalog.pg_extension AS e
  JOIN pg_catalog.pg_namespace AS n ON n.oid = e.extnamespace
  WHERE e.extname = 'unaccent';
  IF v_schema <> 'extensions' THEN
    EXECUTE 'ALTER EXTENSION unaccent SET SCHEMA extensions';
  END IF;
END
$block$;

CREATE TABLE app.categories (
  category_key varchar(50) PRIMARY KEY,
  label varchar(100) NOT NULL,
  image_url varchar(200),
  CONSTRAINT ck_categories_image CHECK (image_url IS NULL OR image_url ~ '^/images/')
);

CREATE TABLE app.products (
  product_id integer PRIMARY KEY,
  name varchar(200) NOT NULL,
  category_key varchar(50) NOT NULL REFERENCES app.categories(category_key),
  price numeric(12,0) NOT NULL CHECK (price >= 0),
  old_price numeric(12,0) CHECK (old_price IS NULL OR old_price > price),
  rating numeric(2,1) NOT NULL CHECK (rating BETWEEN 0 AND 5),
  sold integer NOT NULL DEFAULT 0 CHECK (sold >= 0),
  badge varchar(10) CHECK (badge IS NULL OR badge IN ('hot', 'sale', 'new')),
  description varchar(1000) NOT NULL,
  image_url varchar(200),
  CONSTRAINT ck_products_image CHECK (image_url IS NULL OR image_url ~ '^/images/')
);
CREATE INDEX idx_products_category ON app.products(category_key);
CREATE INDEX idx_products_sold_desc ON app.products(sold DESC);

CREATE TABLE app.product_images (
  product_id integer NOT NULL REFERENCES app.products(product_id) ON DELETE CASCADE,
  sort_order integer NOT NULL CHECK (sort_order > 0),
  url varchar(200) NOT NULL CHECK (url ~ '^/images/'),
  PRIMARY KEY (product_id, sort_order)
);

CREATE TABLE app.product_specs (
  product_id integer NOT NULL REFERENCES app.products(product_id) ON DELETE CASCADE,
  sort_order integer NOT NULL CHECK (sort_order > 0),
  spec_text varchar(300) NOT NULL,
  PRIMARY KEY (product_id, sort_order)
);

CREATE TABLE app.promo_codes (
  code varchar(20) PRIMARY KEY CHECK (code = pg_catalog.upper(pg_catalog.btrim(code))),
  discount_rate numeric(4,3) NOT NULL CHECK (discount_rate > 0 AND discount_rate <= 1),
  is_active boolean NOT NULL DEFAULT true,
  description varchar(200)
);

CREATE TABLE app.orders (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code varchar(10) NOT NULL UNIQUE CHECK (order_code ~ '^DI[0-9]{8}$'),
  delivery_method varchar(10) NOT NULL CHECK (delivery_method IN ('standard', 'express')),
  payment_method varchar(10) NOT NULL CHECK (payment_method IN ('cod', 'transfer')),
  promo_code varchar(20),
  subtotal numeric(12,0) NOT NULL CHECK (subtotal >= 0),
  shipping_fee numeric(12,0) NOT NULL CHECK (shipping_fee >= 0),
  discount numeric(12,0) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total numeric(12,0) GENERATED ALWAYS AS (subtotal - discount + shipping_fee) STORED,
  customer_name varchar(80) NOT NULL CHECK (char_length(btrim(customer_name)) >= 2),
  customer_phone varchar(10) NOT NULL CHECK (customer_phone ~ '^0[0-9]{9}$'),
  customer_address varchar(300) NOT NULL CHECK (char_length(btrim(customer_address)) >= 10),
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_created_desc ON app.orders(created_at DESC);
CREATE INDEX idx_orders_promo ON app.orders(promo_code) WHERE promo_code IS NOT NULL;

CREATE TABLE app.order_items (
  order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES app.orders(order_id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES app.products(product_id),
  product_name varchar(200) NOT NULL,
  unit_price numeric(12,0) NOT NULL CHECK (unit_price >= 0),
  qty integer NOT NULL CHECK (qty BETWEEN 1 AND 99),
  line_total numeric(12,0) GENERATED ALWAYS AS (unit_price * qty) STORED,
  UNIQUE (order_id, product_id)
);
CREATE INDEX idx_order_items_order ON app.order_items(order_id);
CREATE INDEX idx_order_items_product ON app.order_items(product_id);

CREATE OR REPLACE FUNCTION app.fn_tao_don_hang(
  p_customer_name text, p_customer_phone text, p_customer_address text,
  p_delivery_method text, p_payment_method text, p_promo_code text DEFAULT NULL,
  p_note text DEFAULT NULL, p_items jsonb DEFAULT '[]'::jsonb
)
RETURNS TABLE (
  order_id bigint, order_code text, delivery_method text, payment_method text,
  promo_code text, subtotal numeric, shipping_fee numeric, discount numeric, total numeric,
  customer_name text, customer_phone text, customer_address text, note text,
  created_at timestamptz, items jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE
  r record;
  v_locked_count integer := 0;
  v_merged_count integer := 0;
  v_merged_items jsonb;
  v_subtotal numeric(12,0) := 0;
  v_shipping_fee numeric(12,0) := 0;
  v_discount numeric(12,0) := 0;
  v_rate numeric(4,3);
  v_promo text;
  v_applied_promo text;
  v_code text;
  v_order_id bigint;
  v_attempt integer;
BEGIN
  IF pg_catalog.char_length(pg_catalog.btrim(coalesce(p_customer_name, ''))) < 2 THEN
    RAISE EXCEPTION 'Nhập họ tên người nhận.' USING ERRCODE = 'P0001';
  END IF;
  IF coalesce(p_customer_phone, '') !~ '^0[0-9]{9}$' THEN
    RAISE EXCEPTION 'Số điện thoại cần 10 số và bắt đầu bằng 0.' USING ERRCODE = 'P0001';
  END IF;
  IF pg_catalog.char_length(pg_catalog.btrim(coalesce(p_customer_address, ''))) < 10 THEN
    RAISE EXCEPTION 'Nhập địa chỉ giao hàng đầy đủ hơn.' USING ERRCODE = 'P0001';
  END IF;
  IF p_delivery_method IS NULL OR p_delivery_method NOT IN ('standard', 'express') THEN
    RAISE EXCEPTION 'Chọn cách giao hàng hợp lệ.' USING ERRCODE = 'P0001';
  END IF;
  IF p_payment_method IS NULL OR p_payment_method NOT IN ('cod', 'transfer') THEN
    RAISE EXCEPTION 'Chọn cách thanh toán hợp lệ.' USING ERRCODE = 'P0001';
  END IF;
  IF p_items IS NULL OR pg_catalog.jsonb_typeof(p_items) <> 'array' THEN
    RAISE EXCEPTION 'Giỏ hàng trống.' USING ERRCODE = 'P0001';
  END IF;
  IF pg_catalog.jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Giỏ hàng trống.' USING ERRCODE = 'P0001';
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_catalog.jsonb_array_elements(p_items) AS elem
    WHERE CASE
      WHEN pg_catalog.jsonb_typeof(elem) = 'object'
       AND pg_catalog.jsonb_typeof(elem->'id') = 'number'
       AND pg_catalog.jsonb_typeof(elem->'qty') = 'number'
      THEN (elem->>'id')::numeric <> pg_catalog.trunc((elem->>'id')::numeric)
        OR (elem->>'id')::numeric < 1 OR (elem->>'id')::numeric > 2147483647
        OR (elem->>'qty')::numeric <> pg_catalog.trunc((elem->>'qty')::numeric)
        OR (elem->>'qty')::numeric < 1 OR (elem->>'qty')::numeric > 99
      ELSE true
    END
  ) THEN
    RAISE EXCEPTION 'Số lượng mỗi món phải từ 1 đến 99.' USING ERRCODE = 'P0001';
  END IF;

  SELECT pg_catalog.jsonb_agg(
           pg_catalog.jsonb_build_object('product_id', x.product_id, 'qty', x.qty)
           ORDER BY x.product_id)
  INTO v_merged_items
  FROM (
    SELECT (elem->>'id')::integer AS product_id,
           pg_catalog.sum((elem->>'qty')::integer)::bigint AS qty
    FROM pg_catalog.jsonb_array_elements(p_items) AS elem
    GROUP BY (elem->>'id')::integer
  ) AS x;

  IF EXISTS (
    SELECT 1 FROM pg_catalog.jsonb_to_recordset(v_merged_items)
      AS m(product_id integer, qty bigint)
    WHERE m.qty > 99
  ) THEN
    RAISE EXCEPTION 'Số lượng mỗi món phải từ 1 đến 99.' USING ERRCODE = 'P0001';
  END IF;
  SELECT pg_catalog.jsonb_array_length(v_merged_items) INTO v_merged_count;
  IF v_merged_count > 50 THEN
    RAISE EXCEPTION 'Tối đa 50 món mỗi đơn.' USING ERRCODE = 'P0001';
  END IF;

  FOR r IN
    SELECT p.product_id
    FROM app.products AS p
    JOIN pg_catalog.jsonb_to_recordset(v_merged_items) AS m(product_id integer, qty integer)
      ON m.product_id = p.product_id
    ORDER BY p.product_id
    FOR UPDATE OF p
  LOOP
    v_locked_count := v_locked_count + 1;
  END LOOP;
  IF v_locked_count <> v_merged_count THEN
    RAISE EXCEPTION 'Có sản phẩm không tồn tại trong cửa hàng.' USING ERRCODE = 'P0001';
  END IF;

  SELECT coalesce(pg_catalog.sum(p.price * m.qty), 0)
  INTO v_subtotal
  FROM pg_catalog.jsonb_to_recordset(v_merged_items) AS m(product_id integer, qty integer)
  JOIN app.products AS p ON p.product_id = m.product_id;

  IF p_delivery_method = 'express' THEN v_shipping_fee := 45000;
  ELSIF v_subtotal >= 500000 THEN v_shipping_fee := 0;
  ELSE v_shipping_fee := 30000;
  END IF;

  v_promo := pg_catalog.upper(pg_catalog.btrim(coalesce(p_promo_code, '')));
  IF v_promo <> '' THEN
    SELECT pc.discount_rate INTO v_rate
    FROM app.promo_codes AS pc WHERE pc.code = v_promo AND pc.is_active;
    IF v_rate IS NOT NULL THEN
      v_discount := pg_catalog.round(v_subtotal * v_rate);
      v_applied_promo := v_promo;
    END IF;
  END IF;

  FOR v_attempt IN 1..20 LOOP
    v_code := 'DI' || pg_catalog.lpad(
      pg_catalog.floor(pg_catalog.random() * 100000000)::integer::text, 8, '0');
    BEGIN
      INSERT INTO app.orders (
        order_code, delivery_method, payment_method, promo_code, subtotal, shipping_fee,
        discount, customer_name, customer_phone, customer_address, note, created_at
      ) VALUES (
        v_code, p_delivery_method, p_payment_method, v_applied_promo, v_subtotal, v_shipping_fee,
        v_discount, pg_catalog.btrim(p_customer_name), p_customer_phone,
        pg_catalog.btrim(p_customer_address),
        nullif(pg_catalog.btrim(coalesce(p_note, '')), ''), pg_catalog.now()
      ) RETURNING app.orders.order_id INTO v_order_id;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      v_order_id := NULL;
    END;
  END LOOP;
  IF v_order_id IS NULL THEN
    RAISE EXCEPTION 'Không tạo được mã đơn duy nhất.' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO app.order_items(order_id, product_id, product_name, unit_price, qty)
  SELECT v_order_id, m.product_id, p.name, p.price, m.qty
  FROM pg_catalog.jsonb_to_recordset(v_merged_items) AS m(product_id integer, qty integer)
  JOIN app.products AS p ON p.product_id = m.product_id
  ORDER BY m.product_id;

  RETURN QUERY
  SELECT o.order_id, o.order_code::text, o.delivery_method::text, o.payment_method::text,
         o.promo_code::text, o.subtotal, o.shipping_fee, o.discount, o.total,
         o.customer_name::text, o.customer_phone::text, o.customer_address::text, o.note::text,
         o.created_at,
         (SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
            'id', i.product_id, 'name', i.product_name, 'price', i.unit_price, 'qty', i.qty)
            ORDER BY i.product_id)
          FROM app.order_items AS i WHERE i.order_id = o.order_id)
  FROM app.orders AS o WHERE o.order_id = v_order_id;
END;
$fn$;

CREATE VIEW app.vw_san_pham AS
SELECT p.product_id, p.name, p.category_key, c.label AS category_label,
       c.image_url AS category_image_url, p.price, p.old_price, p.rating, p.sold,
       p.badge, p.description, p.image_url,
       coalesce(p.image_url, c.image_url) AS display_image_url
FROM app.products AS p JOIN app.categories AS c ON c.category_key = p.category_key;

CREATE VIEW app.vw_don_hang_chi_tiet AS
SELECT o.order_id, o.order_code, o.created_at, o.delivery_method, o.payment_method,
       o.promo_code, o.subtotal, o.shipping_fee, o.discount, o.total,
       o.customer_name, o.customer_phone, o.customer_address, o.note,
       i.order_item_id, i.product_id, i.product_name, i.unit_price, i.qty, i.line_total
FROM app.orders AS o JOIN app.order_items AS i ON i.order_id = o.order_id;
