CREATE TABLE app.admin_posts (
  post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) NOT NULL,
  slug varchar(220) NOT NULL UNIQUE,
  excerpt varchar(500) NOT NULL DEFAULT '',
  content text NOT NULL,
  status varchar(12) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  image_url varchar(200) CHECK (image_url IS NULL OR image_url ~ '^/images/'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE app.store_settings (
  store_id smallint PRIMARY KEY DEFAULT 1 CHECK (store_id = 1),
  name varchar(160) NOT NULL DEFAULT 'Đồ Cũ Quang Huy',
  phone varchar(30) NOT NULL DEFAULT '',
  address varchar(300) NOT NULL DEFAULT '',
  description varchar(1000) NOT NULL DEFAULT '',
  opening_hours varchar(300) NOT NULL DEFAULT '',
  facebook_url varchar(300) NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO app.store_settings(store_id) VALUES (1) ON CONFLICT (store_id) DO NOTHING;

ALTER TABLE app.orders ADD COLUMN IF NOT EXISTS status varchar(12) NOT NULL DEFAULT 'new';
ALTER TABLE app.orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE app.orders ADD CONSTRAINT orders_status_check CHECK (status IN ('new', 'confirmed', 'shipping', 'completed', 'cancelled'));
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON app.orders(status, created_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON app.products, app.admin_posts, app.store_settings TO app_runtime;
GRANT SELECT, UPDATE ON app.orders TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO app_runtime;