-- 004: Khách hàng (tổng hợp từ đơn hàng), Phản hồi khách, Báo cáo lợi nhuận (giá vốn),
-- Cài đặt hệ thống (phí ship, ngưỡng miễn phí, bảo trì, thông báo).

ALTER TABLE app.products ADD COLUMN IF NOT EXISTS cost_price numeric(12,0) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS app.feedback (
  feedback_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(120) NOT NULL,
  phone varchar(30) NOT NULL DEFAULT '',
  message varchar(1000) NOT NULL,
  rating smallint NOT NULL DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  status varchar(10) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'replied')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON app.feedback(created_at DESC);

CREATE TABLE IF NOT EXISTS app.system_settings (
  setting_id smallint PRIMARY KEY DEFAULT 1 CHECK (setting_id = 1),
  shipping_fee numeric(12,0) NOT NULL DEFAULT 30000,
  free_shipping_threshold numeric(12,0) NOT NULL DEFAULT 500000,
  maintenance_mode boolean NOT NULL DEFAULT false,
  announcement varchar(300) NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO app.system_settings(setting_id) VALUES (1) ON CONFLICT (setting_id) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON app.feedback TO app_runtime;
GRANT SELECT, UPDATE ON app.system_settings TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO app_runtime;

